name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Build the MCP executables
        uses: actions/checkout@v4
        with:
          repository: 'tanin47/legalrabbit-mcpb'
          token: ${{ secrets.MCPB_PRIVATE_REPO_PAT }}
          path: legalrabbit-mcpb
      - name: Build the MCP executables
        run: cd legalrabbit-mcpb && bun install && bun run bun-test && bun run build-mac && bun run build-win
      - name: Set the signature
        run: |
          MCPB_SHA=$(cd legalrabbit-mcpb && git rev-parse HEAD)
          sed -i "s/\[SIGNATURE\]/${MCPB_SHA}/g" ./agents/legalrabbit-docx-subagent.md
      - name: Set the version
        run: |
          sed -i "s/\[VERSION\]/${VERSION}/g" ./.claude-plugin/plugin.json
        env:
          VERSION: ${{ github.event.inputs.tag }}
      - name: Build the agent and skills zip file
        run: zip -r legalrabbit-docx.manifest ./agents ./skills
      - name: Build the Claude plugin zip file
        run: zip -r legalrabbit-docx-claude-plugin.zip ./.claude-plugin ./agents ./skills ./scripts .mcp.json
      - name: Create a release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: false
          draft: false
          files: |
            legalrabbit-docx-claude-plugin.zip
            legalrabbit-docx.manifest
            legalrabbit-mcpb/dist/mac/legalrabbit-docx-mcp
            legalrabbit-mcpb/dist/win/legalrabbit-docx-mcp.exe
          overwrite_files: true
          target_commitish: ${{ github.sha }}
          fail_on_unmatched_files: true
          generate_release_notes: false
          append_body: false
          tag_name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.ref_name }}
