name: release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Build the MCP executables
        uses: actions/checkout@v4
        with:
          repository: 'tanin47/legalrabbit-mcpb'
          token: ${{ secrets.MCPB_PRIVATE_REPO_PAT }}
          path: legalrabbit-mcpb
      - name: Prepare the MCP repo
        run: cd legalrabbit-mcpb && bun install
      - name: Run the tests on the MCP repo
        if: ${{ !endsWith(github.event.inputs.tag, '-dev') }}
        run: cd legalrabbit-mcpb && bun run bun-test
      - name: Build the MCP executables
        run: cd legalrabbit-mcpb && npm run build
      - name: Build the agent and skills zip file
        working-directory: ./plugins/docx
        run: zip -r legalrabbit-docx.manifest ./skills
      - name: Create a release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ endsWith(github.event.inputs.tag, '-dev') }}
          draft: false
          make_latest: false
          files: |
            ./plugins/docx/legalrabbit-docx.manifest
            ./legalrabbit-mcpb/dist/mac/legalrabbit-docx-mcp
            ./legalrabbit-mcpb/dist/win/legalrabbit-docx-mcp.exe
            ./legalrabbit-mcpb/dist/mcpb/legalrabbit-docx.mcpb
          overwrite_files: true
          target_commitish: ${{ github.sha }}
          fail_on_unmatched_files: true
          generate_release_notes: false
          append_body: false
          tag_name: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.ref_name }}
